version: '2.0.{build}.0'

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  parallel: true
  project: 'StaticReflection.sln'
  publish_nuget: true

after_build:
  - cmd: nuget pack ExpressionReflection.nuspec -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
  path: 'ExpressionReflection*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: TFTKac0CbCOvowsFmuUzFjjIcRNJNJnigSh568rlQcjSn2E3JjWbVcobqVD3wGtl
  artifact: /ExpressionReflection.*\.nupkg/
  skip_symbols: false
